version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot-tele:latest
    ports:
      - 3000:3000
    expose:
      - 3000
    stdin_open: true
    tty: true
